# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBjV74m6XhsLiq033u3-3ZJyEhM6JwZY
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN
from imblearn.ensemble import BalancedRandomForestClassifier

url = "https://raw.githubusercontent.com/AnjulaMehto/Sampling_Assignment/main/Creditcard_data.csv"
data = pd.read_csv(url)

X = data.drop("Class", axis=1)
y = data["Class"]

samplers = [
    ("Sampling1", RandomOverSampler(random_state=7)),
    ("Sampling2", RandomUnderSampler(random_state=7)),
    ("Sampling3", SMOTE(random_state=7)),
    ("Sampling4", SMOTEENN(random_state=7)),
    ("Sampling5", "BRF")
]

models = [
    ("M1", LogisticRegression(max_iter=2000)),
    ("M2", DecisionTreeClassifier()),
    ("M3", RandomForestClassifier(n_estimators=150)),
    ("M4", SVC()),
    ("M5", GaussianNB())
]

result = pd.DataFrame(
    index=[m[0] for m in models],
    columns=[s[0] for s in samplers]
)

for s_name, sampler in samplers:

    if s_name == "Sampling5":
        X_res, y_res = X, y
    else:
        X_res, y_res = sampler.fit_resample(X, y)

    X_tr, X_te, y_tr, y_te = train_test_split(
        X_res, y_res, test_size=0.3, random_state=7
    )

    for m_name, model in models:

        if s_name == "Sampling5":
            clf = BalancedRandomForestClassifier(n_estimators=150, random_state=7)
        else:
            clf = model

        clf.fit(X_tr, y_tr)
        pred = clf.predict(X_te)
        acc = accuracy_score(y_te, pred) * 100
        result.loc[m_name, s_name] = round(acc, 2)

print(result)

best_score = result.astype(float).max().max()
best_pair = result.astype(float).stack().idxmax()

print(best_pair[0], best_pair[1], best_score)

print("\n================= FINAL RESULTS =================\n")

display_table = result.copy()
display_table.index.name = "Model"
display_table.columns.name = "Sampling Technique"

print(display_table.to_string())

print("\n================= BEST COMBINATION =================\n")

best_score = display_table.astype(float).max().max()
best_position = display_table.astype(float).stack().idxmax()

print(f"Best Model          : {best_position[0]}")
print(f"Best Sampling Method: {best_position[1]}")
print(f"Best Accuracy (%)   : {best_score:.2f}")

